enyo.depends(
	'kind.Spotlight.Decorator.Container.js',
	'kind.Spotlight.Decorator.List.js',
	'kind.Spotlight.Decorator.GridList.js',
	'kind.Spotlight.Decorator.Checkbox.js',
	'kind.Spotlight.Decorator.MyCheckbox.js',
	'kind.Spotlight.Decorator.Slider.js',
	'kind.Spotlight.Decorator.Picker.js',
	'kind.Spotlight.Decorator.DatePicker.js',
	'kind.Spotlight.Decorator.TimePicker.js',
	'kind.Spotlight.Decorator.Input.js',
	'kind.Spotlight.Decorator.Panels.js'
);